hs.hotkey.bind({"cmd", "ctrl"}, "t", function()
    hs.application.launchOrFocus("iTerm")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "e", function()
    hs.application.launchOrFocus("Emacs")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "g", function()
    hs.application.launchOrFocus("Google Chrome")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "f", function()
    hs.application.launchOrFocus("Finder")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "o", function()
    hs.application.launchOrFocus("Spotify")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "a", function()
    hs.application.launchOrFocus("Google Calendar")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "m", function()
    hs.application.launchOrFocus("Google Mail")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "k", function()
    hs.application.launchOrFocus("Facebook")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "d", function()
    hs.application.launchOrFocus("Todoist")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "r", function()
    hs.application.launchOrFocus("Notion")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "u", function()
    hs.application.launchOrFocus("Visual Studio Code")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "n", function()
    hs.application.launchOrFocus("Google Translate")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "s", function()
    hs.application.launchOrFocus("Instagram")
end)
hs.hotkey.bind({"cmd", "ctrl"}, "h", function()
    hs.application.launchOrFocus("Obsidian")
end)
